export const ROUTE_PREFERENCES: Record<string, string[]> = {
  "markdown->pdf": ["pandoc"],
  "markdown->docx": ["pandoc"],
  "html->pdf": ["pandoc"],
  "html->markdown": ["pandoc"],
  "docx->pdf": ["libreoffice"],
  "pptx->pdf": ["libreoffice"],
  "xlsx->pdf": ["libreoffice"],
  "odt->pdf": ["libreoffice"],
  "ods->pdf": ["libreoffice"],
  "odp->pdf": ["libreoffice"],
  "pdf->markdown": ["markitdown", "docling"],
  "pdf->txt": ["markitdown", "docling"],
  "url->markdown": ["trafilatura", "jina"],
  "url->txt": ["trafilatura"],
  "jpg->png": ["imagemagick"],
  "png->jpg": ["imagemagick"],
  "webp->png": ["imagemagick"],
  "webp->jpg": ["imagemagick"],
  "heic->jpg": ["imagemagick"],
  "heic->png": ["imagemagick"],
  "mp4->mp3": ["ffmpeg"],
  "mov->mp4": ["ffmpeg"],
  "mkv->mp4": ["ffmpeg"],
  "wav->mp3": ["ffmpeg"],
  "mp3->wav": ["ffmpeg"],
  "pdf:merge": ["qpdf"],
  "pdf:split": ["qpdf"],
  "pdf:optimize": ["qpdf"],
  "youtube-url->mp4": ["ytdlp"],
  "youtube-url->mp3": ["ytdlp"],
  "youtube-url->subtitle": ["ytdlp"],
  "mp3->transcript": ["whisper"],
  "wav->transcript": ["whisper"],
  "mp4->transcript": ["whisper"],
  "mov->transcript": ["whisper"],
  "mkv->transcript": ["whisper"]
};

